Dockerfile: Avoid touching external resources
Let's install all the necessary things in the build-* images, so we
don't touch/hammer external servers each time there is a small change in
IGT.

We have already seen this failing:

	Error: Error downloading packages:
	  Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=fedora-30&arch=x86_64
	The command '/bin/sh -c dnf install -y findutils &&         dnf clean all' returned a non-zero code: 1

Cc: Oleg Vasilev <oleg.vasilev@intel.com>
Cc: Petri Latvala <petri.latvala@intel.com>
Signed-off-by: Arkadiusz Hiler <arkadiusz.hiler@intel.com>
Reviewed-by: Petri Latvala <petri.latvala@intel.com>