tests: use an empty brace initializer
In some sandboxes the toolchain complains about missing
braces around initializer, however, using an empty
initializer is enough to shut out the compiler.

../tests/kms_plane_cursor.c: In function '__real_main_302':
../tests/kms_plane_cursor.c:305:2 error: missing braces around
initializer [-Werror=missing-braces]
	data_t data = { 0 };

v2:
   Use an empty initializer { } instead of { 0 } <Petri Latvala>

Signed-off-by: Carlos Santa <carlos.santa@intel.com>
Reviewed-by: Petri Latvala <petri.latvala@intel.com>