tests/i915_pm_freq_api: add missing include
Add missing include file. This fixes armhf, aarch64 and mips
cross-compilation error:

../tests/i915/i915_pm_freq_api.c:80:46: error: ‘O_WRONLY’ undeclared (first use in this function); did you mean ‘STA_RONLY’?

Signed-off-by: Kamil Konieczny <kamil.konieczny@linux.intel.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab@kernel.org>
Reviewed-by: Andrzej Hajda <andrzej.hajda@intel.com>