lib/igt_fb: add missing include in header
Direct include of lib igt_fb header breaks builds with errors

xf86drmMode.h:533:2: error: unknown type name ‘uint32_t’

Fixed it with adding proper include in header.

Cc: Swati Sharma <swati2.sharma@intel.com>
Cc: Petri Latvala <petri.latvala@intel.com>
Signed-off-by: Kamil Konieczny <kamil.konieczny@linux.intel.com>
Reviewed-by: Swati Sharma <swati2.sharma@intel.com>