lib/igt_fb: Fix -Werror=missing-braces compilation on clang.
Clang fails to compile with:
error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]

Make the initializer empty to fix this issue.

Signed-off-by: Maarten Lankhorst <maarten.lankhorst@linux.intel.com>
Reviewed-by: Petri Latvala <petri.latvala@intel.com> #irc