lib/rendercopy_gen*: Make cc/viewport static
Since both rendercopy_gen8.c and rendercopy_gen9.c declare cc/viewport
variables without marking them as static, -fcommon also causes these to
make our builds fail:

/usr/bin/ld:
lib/libigt-rendercopy_gen9_c.a(rendercopy_gen9.c.o):lib/rendercopy_gen9.c:46:
multiple definition of `cc';
lib/libigt-rendercopy_gen8_c.a(rendercopy_gen8.c.o):lib/rendercopy_gen8.c:45:
first defined here
/usr/bin/ld:
lib/libigt-rendercopy_gen9_c.a(rendercopy_gen9.c.o):lib/rendercopy_gen9.c:51:
multiple definition of `viewport';
lib/libigt-rendercopy_gen8_c.a(rendercopy_gen8.c.o):lib/rendercopy_gen8.c:50:
first defined here

So, fix this by marking them as static.

Reviewed-by: Chris Wilson <chris@chris-wilson.co.uk>
Signed-off-by: Lyude Paul <lyude@redhat.com>