.gitlab-ci: Switch to podman/buildah/skopeo
The current setup uses docker-inside-docker setup which seems to fail
quite often:
	WARNING: Service runner-HnMPegeT-project-3185-concurrent-0-docker-0 probably didn't start properly.
	Using docker image XYZ for docker:stable ...
	ERROR: Job failed (system failure): Error response from daemon: No such container: XYZ (executor_docker.go:743:0s)

Switching over to buildah (invoked via podman - docker's drop-in
replacement) everything will happen locally without the need to engage
any daemons, which should make the build more reliable.

We force using docker format for the containers as only the very latest
docker can understand OCI and it does not have widespread adoption yet.

Buildah can also use chroot for isolation which simplifies network
handling for nested containers and have a potential of being a tad bit
faster.

To query remotes and manage remote tags we can use skopeo, which saves
us from pulling full images from the remote without an actual need.

Fixes: https://gitlab.freedesktop.org/freedesktop/freedesktop/issues/187
Signed-off-by: Arkadiusz Hiler <arkadiusz.hiler@intel.com>
Reviewed-by: Petri Latvala <petri.latvala@intel.com>