meson: intel_dp_compliance depends on libudev
Only build intel_dp_compliance when libudev is available, also include
libudev in the list of dependencies.

Fixes error when libudev isn't there:

../tools/intel_dp_compliance_hotplug.c:33:21: fatal error: libudev.h: No such file or directory
 #include <libudev.h>

Signed-off-by: Jani Nikula <jani.nikula@intel.com>
Reviewed-by: Arkadiusz Hiler <arkadiusz.hiler@intel.com>