lib/intel_memory_region: Fix missing header inclusion
IGT commit 68efa99c62e2 ("i915/gem_eio: Exercise object creation while
wedged") extended lib/i915/intel_memory_region.h header with a definition
of new struct gem_memory_region.  That structure contains a member of type
struct drm_i915_gem_memory_class_instance, but definition of that type is
not available unless "i915_drm.h" header is included.  Include the missing
header.

../lib/i915/intel_memory_region.h:118:44: error: field ‘ci’ has incomplete type
  118 |  struct drm_i915_gem_memory_class_instance ci;

Signed-off-by: Janusz Krzysztofik <janusz.krzysztofik@linux.intel.com>
Reviewed-by: Petri Latvala <petri.latvala@intel.com>